language: php

php:
    - "7.2"
    - hhvm
    - nightly

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm

sudo: false

git:
    submodules: false

before_script:
    - composer install -n --prefer-dist

script:
    - phpunit --configuration .phpunit.xml
